export enum LocalStorageKeys {
    REFRESH_TOKEN = 'REFRESH_TOKEN',
    ACCESS_TOKEN = 'ACCESS_TOKEN',
    AUTH_SESSION_ID = 'AUTH_SESSION_ID',
    SFTP_SCREEN_MODE = 'SFTP_SCREEN_MODE',
    TERMINAL_SCREEN_MODE = 'TERMINAL_SCREEN_MODE',
    TERMINAL_SESSIONS_GROUPS = 'TERMINAL_SESSIONS_GROUPS'
}
